//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NicoV4.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NicoV4.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   hh\:mm\:ss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string F_HHMMSS {
            get {
                return ResourceManager.GetString("F_HHMMSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yy/MM/dd HH:mm:ss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string F_YYMMDDHHMMSS {
            get {
                return ResourceManager.GetString("F_YYMMDDHHMMSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyy/MM/dd HH:mm:ss に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string F_YYYYMMDDHHMMSS {
            get {
                return ResourceManager.GetString("F_YYYYMMDDHHMMSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_ADD {
            get {
                return ResourceManager.GetString("L_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Children に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_ADD_CHILDREN {
            get {
                return ResourceManager.GetString("L_ADD_CHILDREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイリスト追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_ADD_MYLIST {
            get {
                return ResourceManager.GetString("L_ADD_MYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_CANCEL {
            get {
                return ResourceManager.GetString("L_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カテゴリタグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_CATEGORY_TAG {
            get {
                return ResourceManager.GetString("L_CATEGORY_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_COMMENT_COUNTER {
            get {
                return ResourceManager.GetString("L_COMMENT_COUNTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Urlをコピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_COPY_URL {
            get {
                return ResourceManager.GetString("L_COPY_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   著作権 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_COPYRIGHT {
            get {
                return ResourceManager.GetString("L_COPYRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_DELETE {
            get {
                return ResourceManager.GetString("L_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_DESCRIPTION {
            get {
                return ResourceManager.GetString("L_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_DOWNLOAD {
            get {
                return ResourceManager.GetString("L_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JUMP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_JUMP {
            get {
                return ResourceManager.GetString("L_JUMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_LENGTH_SECONDS {
            get {
                return ResourceManager.GetString("L_LENGTH_SECONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_LOGIN {
            get {
                return ResourceManager.GetString("L_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メールアドレス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_MAIL_ADDRESS {
            get {
                return ResourceManager.GetString("L_MAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Menu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_MENU {
            get {
                return ResourceManager.GetString("L_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mp3へ変換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_MP3_CONVERT {
            get {
                return ResourceManager.GetString("L_MP3_CONVERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_MYLIST_COUNTER {
            get {
                return ResourceManager.GetString("L_MYLIST_COUNTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_NAME {
            get {
                return ResourceManager.GetString("L_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_OK {
            get {
                return ResourceManager.GetString("L_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_PASSWORD {
            get {
                return ResourceManager.GetString("L_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_REMOVE {
            get {
                return ResourceManager.GetString("L_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_RENAME {
            get {
                return ResourceManager.GetString("L_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_SEARCH {
            get {
                return ResourceManager.GetString("L_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タグ検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_SEARCH_TAG {
            get {
                return ResourceManager.GetString("L_SEARCH_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ワード検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_SEARCH_WORD {
            get {
                return ResourceManager.GetString("L_SEARCH_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダ選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_SELECT_DIRECTORY {
            get {
                return ResourceManager.GetString("L_SELECT_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_START_TIME {
            get {
                return ResourceManager.GetString("L_START_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_STATUS {
            get {
                return ResourceManager.GetString("L_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   とりあえずマイリストに追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_TEMPORARY_ADD {
            get {
                return ResourceManager.GetString("L_TEMPORARY_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   とりあえずマイリストから削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_TEMPORARY_DELETE {
            get {
                return ResourceManager.GetString("L_TEMPORARY_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サムネイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_THUMBNAIL {
            get {
                return ResourceManager.GetString("L_THUMBNAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_TITLE {
            get {
                return ResourceManager.GetString("L_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログイン設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_TITLE_LOGIN {
            get {
                return ResourceManager.GetString("L_TITLE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_TITLE_VERSION {
            get {
                return ResourceManager.GetString("L_TITLE_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_UPDATEDATE {
            get {
                return ResourceManager.GetString("L_UPDATEDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_USER_ID {
            get {
                return ResourceManager.GetString("L_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_USER_NAME {
            get {
                return ResourceManager.GetString("L_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_VERSION {
            get {
                return ResourceManager.GetString("L_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string L_VIEW_COUNTER {
            get {
                return ResourceManager.GetString("L_VIEW_COUNTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加するフォルダ名を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_ADD_CHILDREN_DESCRIPTION {
            get {
                return ResourceManager.GetString("M_ADD_CHILDREN_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加するマイリストのUrlを入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_ADD_MYLIST {
            get {
                return ResourceManager.GetString("M_ADD_MYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加したい動画のURLか &quot;sm&quot; から始まる動画IDを入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_ADD_TEMPORARY {
            get {
                return ResourceManager.GetString("M_ADD_TEMPORARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイリストを追加するフォルダを選択してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_MYLIST_SELECT_DIALOG_DESCRIPTION {
            get {
                return ResourceManager.GetString("M_MYLIST_SELECT_DIALOG_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択したフォルダを削除します。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_REMOVE_DESCRIPTION {
            get {
                return ResourceManager.GetString("M_REMOVE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変更後の名前を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string M_RENAME_DESCRIPTION {
            get {
                return ResourceManager.GetString("M_RENAME_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべて に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_ALL {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   動物 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_ANIMAL {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_ANIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アニメ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_ANIME {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_ANIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_CHAT {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_CHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   料理 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_COOKING {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_COOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   踊ってみた に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_DANCE {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_DANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日記 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_DIARY {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_DIARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ent に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_ENT {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_ENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ゲーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_GAME {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   歴史 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_HISTORY {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   lecture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_LECTURE {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_LECTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音楽 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_MUSIC {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_MUSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自然 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_NATURE {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_NATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   other に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_OTHER {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_PLAY {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   politics に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_POLITICS {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_POLITICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   que に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_QUE {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_QUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   R-18 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_R18 {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_R18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ラジオ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_RADIO {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_RADIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   科学 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_SCIENCE {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_SCIENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   歌ってみた に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_SING {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_SING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スポーツ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_SPORT {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_SPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   test に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_TEST {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tw に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_CATEGORY_TW {
            get {
                return ResourceManager.GetString("RANK_CATEGORY_TW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_PERIOD_DAILY {
            get {
                return ResourceManager.GetString("RANK_PERIOD_DAILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_PERIOD_HOURLY {
            get {
                return ResourceManager.GetString("RANK_PERIOD_HOURLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_PERIOD_MONTHLY {
            get {
                return ResourceManager.GetString("RANK_PERIOD_MONTHLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_PERIOD_TOTAL {
            get {
                return ResourceManager.GetString("RANK_PERIOD_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   週間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_PERIOD_WEEKLY {
            get {
                return ResourceManager.GetString("RANK_PERIOD_WEEKLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   総合 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_TARGET_FAV {
            get {
                return ResourceManager.GetString("RANK_TARGET_FAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイリスト数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_TARGET_MYLIST {
            get {
                return ResourceManager.GetString("RANK_TARGET_MYLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメント数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_TARGET_RES {
            get {
                return ResourceManager.GetString("RANK_TARGET_RES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RANK_TARGET_VIEW {
            get {
                return ResourceManager.GetString("RANK_TARGET_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメントが新しい順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_COMMENT0 {
            get {
                return ResourceManager.GetString("SORT_COMMENT0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメントが古い順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_COMMENT1 {
            get {
                return ResourceManager.GetString("SORT_COMMENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメントが多い順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_COMMENTRES0 {
            get {
                return ResourceManager.GetString("SORT_COMMENTRES0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コメントが少ない順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_COMMENTRES1 {
            get {
                return ResourceManager.GetString("SORT_COMMENTRES1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生時間が長い順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_LENGTH0 {
            get {
                return ResourceManager.GetString("SORT_LENGTH0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生時間が短い順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_LENGTH1 {
            get {
                return ResourceManager.GetString("SORT_LENGTH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイリストコメント昇順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_MYCOMMENT0 {
            get {
                return ResourceManager.GetString("SORT_MYCOMMENT0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイリストコメント降順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_MYCOMMENT1 {
            get {
                return ResourceManager.GetString("SORT_MYCOMMENT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録が古い順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_MYREG0 {
            get {
                return ResourceManager.GetString("SORT_MYREG0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録が新しい順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_MYREG1 {
            get {
                return ResourceManager.GetString("SORT_MYREG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイリスト登録が多い順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_MYREGRES0 {
            get {
                return ResourceManager.GetString("SORT_MYREGRES0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マイリスト登録が少ない順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_MYREGRES1 {
            get {
                return ResourceManager.GetString("SORT_MYREGRES1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル昇順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_TITLE0 {
            get {
                return ResourceManager.GetString("SORT_TITLE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイトル降順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_TITLE1 {
            get {
                return ResourceManager.GetString("SORT_TITLE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投稿が新しい順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_UPLOAD0 {
            get {
                return ResourceManager.GetString("SORT_UPLOAD0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投稿が古い順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_UPLOAD1 {
            get {
                return ResourceManager.GetString("SORT_UPLOAD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生数が多い順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_VIEWRES0 {
            get {
                return ResourceManager.GetString("SORT_VIEWRES0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再生数が少ない順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SORT_VIEWRES1 {
            get {
                return ResourceManager.GetString("SORT_VIEWRES1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サムネ大 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string THUMB_SIZE_L {
            get {
                return ResourceManager.GetString("THUMB_SIZE_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サムネ中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string THUMB_SIZE_M {
            get {
                return ResourceManager.GetString("THUMB_SIZE_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サムネ小 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string THUMB_SIZE_S {
            get {
                return ResourceManager.GetString("THUMB_SIZE_S", resourceCulture);
            }
        }
    }
}
